apiVersion: v2
name: django-app-monitoring
description: A Django web app with MySQL database on local Kubernetes cluster compatible with prometheus 
type: application
version: 0.1.3
appVersion: "1.0.0"
