namespace: django-app
# Default values for django-app.
replicaCount: 1

# This sets the container image 
image:
  django:
    repository: mhe5/django-k8s-custom-web
    pullPolicy: IfNotPresent
    tag: "latest"
  nginx:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  mysql:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "8.3"
# name overrides
nameOverride: ""
fullnameOverride: ""

# ingress
ingress:
  enabled: false

# hostpath for volumes
hostpath:
  data: "/run/desktop/mnt/host/c/temp/k8s/db-data/"
  staticfiles: "/run/desktop/mnt/host/c/temp/k8s/static"

# service type and port
service:
  name: django-web-service
  type: NodePort
  port: 80
  nodePort: 30005

# Django app settings
django:
  secretKey: "django-insecure-v966rxdmv_phocaurd%))rr))!x%wvl6ms85+_f=$!^g(2n9o2"
  DB_ENGINE: "django.db.backends.mysql"
  DB_PORT: "3306"
  DB_HOST: "mysql-svc"
  STATIC_ROOT: "/data/static"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,django-svc.django-app.svc.cluster.local"
  CSRF_TRUSTED_ORIGINS: "http://localhost:30005"

# DB secrets
mysql:
  MYSQL_ROOT_PASSWORD: ZGF0YWJhc2U0TWU=
  MYSQL_DATABASE: bGl0dGxlbGVtb24=
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: ZW1wbG95ZWVAMTIz

