apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: "{{- .Values.namespace}}"
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  
  storageClassName: "{{ .Values.storageClassName.database }}"
  accessModes:
    - "{{ .Values.accessMode.database }}"
  resources:
    requests:
      storage: "{{ .Values.storageSize.database }}"
  volumeName: mysql-pv