apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: "{{- .Values.namespace}}"
  labels:
    type: local
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  storageClassName: "{{ .Values.storageClassName.database }}"
  capacity:
    storage: "{{ .Values.storageSize.database }}"
  accessModes:
    - "{{ .Values.accessMode.database }}"
  hostPath:
    path: "{{ .Values.hostpath.database }}"