apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: "{{- .Values.namespace}}"
  labels:
    type: local
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hostpath.data }}"