apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: "{{- .Values.namespace}}"
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "{{- .Values.mysql.MYSQL_ROOT_PASSWORD -}}"
  MYSQL_DATABASE: "{{- .Values.mysql.MYSQL_DATABASE -}}"
  MYSQL_USER: "{{- .Values.mysql.MYSQL_USER -}}"
  MYSQL_PASSWORD: "{{- .Values.mysql.MYSQL_PASSWORD -}}"