prometheus:
  persistentVolume:
    size: 2Gi
  service:
    servicePort: 80
    type: NodePort
    nodePort: 30008
alertmanager:
  persistentVolume:
    size: 1Gi

grafana:
  service:
    type: NodePort  
    port: 30009
