apiVersion: v1
kind: Service
metadata:
  name: django-svc
  namespace: "{{- .Values.namespace}}"
  labels: 
    app: app-svc
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: django-app
  