apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
  namespace: "{{- .Values.namespace}}"
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  storageClassName: "{{ .Values.storageClassName.staticfiles }}"
  accessModes:
    - "{{ .Values.accessMode.staticfiles }}"
  resources:
    requests:
      storage: "{{ .Values.storageSize.staticfiles }}"
  volumeName: staticfiles-pv