apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: django-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGF0YWJhc2U0TWU=
  MYSQL_DATABASE: bGl0dGxlbGVtb24=
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: ZW1wbG95ZWVAMTIz