apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: django-app
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/temp/k8s/db-data/"