apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: django-app
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'echo $(ls -A /var/lib/mysql/)']
        volumeMounts:
        - name: db-data
          mountPath: "/var/lib/mysql/"
      containers:
      - name: mysql
        image: mysql:8.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql/
            name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysql-pvc