apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: "{{- .Values.namespace}}"
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location /static/ {
        alias /data/static/;
      }

      location /metrics {
        deny all;
        access_log off;
        error_log off;
      }

      location / {
        proxy_pass http://django-svc:8000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

    }