apiVersion: v1
kind: Service
metadata:
  name: django-svc
  namespace: django-app
  labels: 
    app: app-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: django-app
  