name: "Development pipeline"
on:
  push:
    branches:
      - main
    paths:
      - 'littlelemon/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'Helm-chart/**'
      - '!Helm-chart/Chart.yaml'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  # run only if some chart file was changed
  test:
    name: Django test
    runs-on: ubuntu-latest
    env:
      DB_PORT : "3306"
      DB_HOST : "127.0.0.1"
      STATIC_ROOT : "/data/static"
      DEBUG : "False"
      ALLOWED_HOSTS : "localhost"
      CSRF_TRUSTED_ORIGINS : "http://localhost:30005"
      DJANGO_SECRET_KEY : 'django-insecure'
      DB_ENGINE : 'django.db.backends.sqlite3'
      MYSQL_DATABASE: 'littlelemon'
      MYSQL_USER : 'littlelemon' 
      MYSQL_PASSWORD : 'littlelemon@123'   
      DB_OPTIONS : '{}'

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            chart-files-changed:
              - 'Helm-chart/**'

      - name: install python
        if: steps.filters.outputs.chart-files-changed == 'false'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - if: steps.filters.outputs.chart-files-changed == 'false'
        name: Install dependencies &  run tests
        run: |
          sudo apt-get update
          sudo apt-get install python3-dev default-libmysqlclient-dev build-essential pkg-config
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 littlelemon/manage.py test restaurant.tests
          
  push_and_scan:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      security-events: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: mhe5/django-k8s-custom-web:${{ github.RUN_NUMBER }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/mhe5/django-k8s-custom-web:${{ github.RUN_NUMBER }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push to Docker Hub
        run: docker push mhe5/django-k8s-custom-web:${{ github.RUN_NUMBER }}
      
      - name: Update Helm chart
        run: |
          INCREMENT_TYPE=${{vars.INCREMENT_TYPE}}
          FILE="Helm-chart/Chart.yaml"
          CURRENT_VERSION=$(grep oP "(?<=version:) \d\.\d.\d{1,3}" $FILE)
          major=$(echo $CURRENT_VERSION | cut -d. -f1)
          minor=$(echo $CURRENT_VERSION | cut -d. -f2)
          patch=$(echo $CURRENT_VERSION | cut -d. -f3)
          if ["INCREMENT_TYPE" == "major"]; then
            major=$major+1
          elif ["INCREMENT_TYPE" == "minor"]; then
            minor=$minor+1
          else
            patch=$patch+1
          fi
          NEW_VERSION=$major.$minor.$patch
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" Helm-chart/values.yaml
          sed -i "s/tag: .*/tag: ${{ github.RUN_NUMBER }}/" Helm-chart/values.yaml
          
      - name: Run the Action
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_message: "Helm chart version updated by GitHub Actions"
          force: false
          target_branch: main
